[package]
name = "sprohk_ast"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bumpalo.workspace = true

sprohk_core = { path = "../core" }
sprohk_lexer = { path = "../lexer" }
