[package]
name = "sprohk_lexer"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
sprohk_core = { path = "../core" }

[[bin]]
name = "lexer_snapshots"
path = "src/bin/gen_snapshots.rs"
